### PR TITLE
Added REST-based container adapters

### PR DESCRIPTION
**Pull request by pzampino**
I've implemented managed and remote container adapters based on WebLogic Server's REST management API. These work with version 12.1.3 and later (though, for 12.1.3, the REST API must be explicitly enabled first). This also resolves the prior limitation of the remote adapters wrt deployment to another host.

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Nice! 

Any idea how these relate to this change? https://github.com/arquillian/arquillian-container-wls/pull/23

**Comment by pzampino** [comment]
There was some work done to better organize the adapters (the change you've
cited), but those are all still the JMX-based implementations.

These new ones I've implemented are based on the REST management API, and
there is some overlap wrt supported versions. We may like to get rid of the
JMX-based adapters (at least for 12.1.3+) at some point, but I don't think
that's necessary at this time.

**Comment by pzampino** [comment]
I have a couple of questions:

1. I've made some changes on top of those in my most recent pull request.
These are to address some deployment issues I noticed while running the CDI
TCK with the REST-based adapters. Should I revoke my prior pull request,
and create a new one? Or, should I just submit a new pull request with only
the newest changes, assuming that the first one will be integrated first?

2. Do you have any idea when these changes will be integrated so they are
more readily available?

Thanks in advance,
   Phil

**Comment by aslakknutsen** [comment]
1. Just append to this branch/pull request for now.

2. Waiting on some feedback from Steve on the naming/usage of this adapter compared to the others.

**Comment by pzampino** [comment]
Ok, I believe I've appended the new changes to this request. Thanks.

**Comment by buttso** [comment]
Hi Aslak - I used this adapter at our recent OOW conference and it looked like it generated quite a bit of interest.  I commented via email on the naming model it uses. Summary is that I'm happy with it and would love to see this get promoted to final as soon as we can.

**Comment by aslakknutsen** [comment]
Excellent.. Pushed upstream. Thank you

**Pull request closed without merging**
