### PR TITLE
Fixed response media type check for error cases

### PR DESCRIPTION
**Pull request by pzampino**
The previous comparison of response media type was incorrect, and for negative test cases, it yielded the wrong behavior wrt some CDI 1.1 TCK tests.

### CODE REVIEW

**Comment by aslakknutsen** [comment]
This is the only commit you added after the previous merge, correct?
https://github.com/pzampino/arquillian-container-wls/commit/a35cd49cf6d98e23ad78700cb38cd4987f369821

**Comment by pzampino** [comment]
Yes, that is correct.

**Comment by aslakknutsen** [comment]
If you have no new changes in your local master branch, could you execute the following to realign with upstream/master;

    git fetch upstream && git reset --hard upstream/master

**Comment by pzampino** [comment]
I've done this. Let me know if there is anything else needed from me.

Thank you,
  Phil

**Comment by aslakknutsen** [comment]
Cool. We'll see how it turned out when next pull request comes in :)

**Comment by pzampino** [comment]
Are you saying that you would like me to submit another pull request?

**Comment by aslakknutsen** [comment]
Not for this specifically no. That's done. But Pull Request in general, for what ever other fixes/features are always welcome.. hehe

**Comment by pzampino** [comment]
I understand. Thanks for committing the change. When do you think it might
be generally available in a release? We would like to use it internally to
run CDI TCK tests. No rush; just trying to get a ballpark idea.

Thanks again,
     Phil

**Comment by aslakknutsen** [comment]
1.0.1.Final released :)

**Comment by pzampino** [comment]
Great!

**Comment by pzampino** [comment]
How is documentation handled for these adapters? I've added some
properties, and there are details which could use some explanation.

**Comment by aslakknutsen** [comment]
@pzampino You can add it to the root README for now; https://github.com/arquillian/arquillian-container-wls/blob/master/README.adoc

**Pull request closed without merging**
